robot:
  type: a1z
  id: a1z_dual
  left_can: can0
  right_can: can1
  cameras:
    top_rgb:
      type: intelrealsense
      serial_number_or_name: "025222071608"
      width: 640
      height: 480
      fps: 30
      color_mode: rgb
      use_depth: false
    left_wrist_rgb:
      type: intelrealsense
      serial_number_or_name: "260522273365"
      width: 640
      height: 480
      fps: 30
      color_mode: rgb
      use_depth: false
    right_wrist_rgb:
      type: intelrealsense
      serial_number_or_name: "CONFIGURE_RIGHT_D405_SERIAL"
      width: 640
      height: 480
      fps: 30
      color_mode: rgb
      use_depth: false
  ema_alpha: 0.3
  max_joint_delta: 0.05
  gripper_start_hold: true
  return_home_on_disconnect: false
  open_grippers_on_disconnect: false

teleop:
  type: bi_a1z_leader
  id: a1z_bi_leader
  left_id: a1z_left_leader
  right_id: a1z_right_leader
  left_arm_config:
    port: /dev/ttyACM0
    joint_signs: [-1, 1, 1, 1, 1, -1]
    joint_scales: [1, 1, 1, 1, 1, 1]
    joint_offsets_rad: [-0.040418965, 1.567886653, -1.698370257, -0.144229406, -0.011507665, -0.016411362]
  right_arm_config:
    port: /dev/ttyACM1
    joint_signs: [-1, 1, 1, 1, 1, -1]
    joint_scales: [1, 1, 1, 1, 1, 1]
    joint_offsets_rad: [-0.040418965, 1.567886653, -1.698370257, -0.144229406, -0.011507665, -0.016411362]

dataset:
  repo_id: local/a1z_dual
  single_task: Coordinate both arms to perform the same task in every episode
  root: datasets/a1z_dual
  fps: 30
  episode_time_s: 60
  reset_time_s: 30
  num_episodes: 50
  video: true
  push_to_hub: false
  num_image_writer_processes: 0
  num_image_writer_threads_per_camera: 4

display_data: true
play_sounds: true
